baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'adesso docs site'
theme = "hugo-theme-learn"
ordersectionsby = "weight"
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true